//This is dummy data that should be replaced with actual data from an API
const videos = [
  {
    id: 1,
    title: "Mercedes S-Class Unveil",
    description:
      "The new Mercedes S-Class is here! Check out the latest features and design.",
    channel: "Mercedes-Benz",
    views: 123456,
    uploadDate: "1 day ago",
    thumbnail: "https://i.ytimg.com/vi/dQw4w9WgXcQ/default.jpg",
  },
  {
    id: 2,
    title: "Top 10 Coding Practices",
    description: "Improve your coding skills with these top 10 practices.",
    channel: "CodeAcademy",
    views: 98500,
    uploadDate: "2 days ago",
    thumbnail: "https://i.ytimg.com/vi/B7Erik2vK0E/default.jpg",
  },
  {
    id: 3,
    title: "The Future of Space Exploration",
    description: "What will space exploration look like in the next 50 years?",
    channel: "NASA",
    views: 154320,
    uploadDate: "3 days ago",
    thumbnail: "https://i.ytimg.com/vi/qH48F9WzvtU/default.jpg",
  },
  {
    id: 4,
    title: "Healthy Meal Prep Ideas",
    description: "Quick and healthy meal prep ideas for the week.",
    channel: "Healthy Eats",
    views: 78500,
    uploadDate: "4 days ago",
    thumbnail: "https://i.ytimg.com/vi/WPdJXoytw7A/default.jpg",
  },
  {
    id: 5,
    title: "JavaScript Async Explained",
    description: "Understanding asynchronous JavaScript with examples.",
    channel: "JS Mastery",
    views: 45000,
    uploadDate: "5 days ago",
    thumbnail: "https://i.ytimg.com/vi/Ptbk2af68e8/default.jpg",
  },
  {
    id: 6,
    title: "2024 Electric Car Lineup",
    description: "A sneak peek into the 2024 electric car models.",
    channel: "AutoReview",
    views: 230000,
    uploadDate: "6 days ago",
    thumbnail: "https://i.ytimg.com/vi/8eWJiP2VSqA/default.jpg",
  },
  {
    id: 7,
    title: "History of the Internet",
    description: "A documentary on the history and evolution of the internet.",
    channel: "TechHistory",
    views: 112000,
    uploadDate: "1 week ago",
    thumbnail: "https://i.ytimg.com/vi/9hVOWcDxbzs/default.jpg",
  },
  {
    id: 8,
    title: "Yoga for Beginners",
    description: "A complete guide to getting started with yoga.",
    channel: "YogaWithAdriene",
    views: 95000,
    uploadDate: "1 week ago",
    thumbnail: "https://i.ytimg.com/vi/v7AYKMP6rOE/default.jpg",
  },
  {
    id: 9,
    title: "Top 10 Travel Destinations 2024",
    description: "Explore the top 10 travel destinations for 2024.",
    channel: "TravelPlus",
    views: 120000,
    uploadDate: "2 weeks ago",
    thumbnail: "https://i.ytimg.com/vi/kYpYHEahjRI/default.jpg",
  },
  {
    id: 10,
    title: "Building a Gaming PC",
    description: "Step-by-step guide to building your own gaming PC.",
    channel: "PC Builder",
    views: 110000,
    uploadDate: "2 weeks ago",
    thumbnail: "https://i.ytimg.com/vi/8yZQweO2vJ4/default.jpg",
  },
  {
    id: 11,
    title: "Advanced Photoshop Techniques",
    description: "Learn advanced techniques in Adobe Photoshop.",
    channel: "DesignTutorials",
    views: 88000,
    uploadDate: "3 weeks ago",
    thumbnail: "https://i.ytimg.com/vi/cIDQJhB-DRY/default.jpg",
  },
  {
    id: 12,
    title: "Investing for Beginners",
    description: "A guide to getting started with investing.",
    channel: "Finance101",
    views: 140000,
    uploadDate: "3 weeks ago",
    thumbnail: "https://i.ytimg.com/vi/0omGZmYDtJA/default.jpg",
  },
  {
    id: 13,
    title: "Understanding Blockchain Technology",
    description: "A deep dive into how blockchain technology works.",
    channel: "CryptoExplain",
    views: 75000,
    uploadDate: "1 month ago",
    thumbnail: "https://i.ytimg.com/vi/SSo_EIwHSd4/default.jpg",
  },
  {
    id: 14,
    title: "Beginner's Guide to Meditation",
    description: "Learn how to start meditating with this beginner's guide.",
    channel: "Calm Mind",
    views: 67000,
    uploadDate: "1 month ago",
    thumbnail: "https://i.ytimg.com/vi/g_1IZ8-kvDI/default.jpg",
  },
  {
    id: 15,
    title: "The Art of Minimalism",
    description: "Embrace minimalism and declutter your life.",
    channel: "Minimalist Life",
    views: 81000,
    uploadDate: "1 month ago",
    thumbnail: "https://i.ytimg.com/vi/t1_lF5KjU9k/default.jpg",
  },
];

const fetchVideos = () => {
  return videos;
};

export default fetchVideos;
